CREATE OR REPLACE VIEW MART.PAYMENT_ANALYSIS AS
SELECT 
    P.PAYMENT_METHOD,
    P.PAYMENT_STATUS,
    P.CURRENCY,
    COUNT(*) AS total_transactions,
    SUM(P.PAYMENT_AMOUNT) AS total_amount,
    AVG(P.PAYMENT_AMOUNT) AS avg_transaction_amount,
    SUM(CASE WHEN P.IS_PAYMENT_SUCCESSFUL THEN 1 ELSE 0 END) AS successful_payments,
    ROUND(SUM(CASE WHEN P.IS_PAYMENT_SUCCESSFUL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS success_rate
FROM GOLD.FACT_PAYMENTS P
GROUP BY P.PAYMENT_METHOD, P.PAYMENT_STATUS, P.CURRENCY
ORDER BY total_amount DESC;
