CREATE OR REPLACE VIEW MART.PAYMENT_ANALYSIS AS
SELECT 
    P.PAYMENT_METHOD,
    P.PAYMENT_STATUS,
    P.ORIGINAL_CURRENCY,
    COUNT(*) AS total_transactions,
    SUM(P.PAYMENT_AMOUNT_USD) AS total_amount_usd,
    AVG(P.PAYMENT_AMOUNT_USD) AS avg_transaction_amount_usd,
    SUM(CASE WHEN P.IS_PAYMENT_SUCCESSFUL THEN 1 ELSE 0 END) AS successful_payments,
    ROUND(SUM(CASE WHEN P.IS_PAYMENT_SUCCESSFUL THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS success_rate
FROM GOLD.FACT_PAYMENTS P
GROUP BY P.PAYMENT_METHOD, P.PAYMENT_STATUS, P.ORIGINAL_CURRENCY
ORDER BY total_amount_usd DESC;
