CREATE OR REPLACE TABLE SILVER.CUSTOMERS AS
SELECT 
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    TRIM(FIRST_NAME || ' ' || LAST_NAME) AS FULL_NAME,
    LOWER(TRIM(EMAIL)) AS EMAIL,
    TRIM(PHONE) AS PHONE,
    UPPER(TRIM(COUNTRY)) AS COUNTRY,
    TO_TIMESTAMP(CREATED_AT) AS CUSTOMER_CREATED_AT,
    CASE 
        WHEN UPPER(IS_ACTIVE) = 'TRUE' THEN TRUE
        WHEN UPPER(IS_ACTIVE) = 'FALSE' THEN FALSE
        ELSE NULL
    END AS IS_ACTIVE,
    CASE WHEN EMAIL IS NULL OR TRIM(EMAIL) = '' THEN TRUE ELSE FALSE END AS IS_EMAIL_MISSING,
    CASE WHEN PHONE IS NULL OR TRIM(PHONE) = '' THEN TRUE ELSE FALSE END AS IS_PHONE_MISSING,
    CURRENT_TIMESTAMP() AS SILVER_LOAD_TIMESTAMP,
    'BRONZE.CUSTOMERS' AS SOURCE_TABLE
FROM BRONZE.CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_ID ORDER BY CREATED_AT DESC) = 1;
