CREATE OR REPLACE TABLE SILVER.PRODUCTS AS
SELECT 
    PRODUCT_ID,
    TRIM(PRODUCT_NAME) AS PRODUCT_NAME,
    COALESCE(NULLIF(TRIM(CATEGORY), ''), 'UNCATEGORIZED') AS CATEGORY,
    CASE 
        WHEN PRICE < 0 THEN NULL
        ELSE PRICE 
    END AS PRICE,
    UPPER(TRIM(CURRENCY)) AS CURRENCY,
    CASE 
        WHEN UPPER(IS_ACTIVE) = 'TRUE' THEN TRUE
        WHEN UPPER(IS_ACTIVE) = 'FALSE' THEN FALSE
        ELSE TRUE
    END AS IS_ACTIVE,
    TO_TIMESTAMP(CREATED_AT) AS PRODUCT_CREATED_AT,
    CASE WHEN PRICE IS NULL OR PRICE < 0 THEN TRUE ELSE FALSE END AS IS_PRICE_INVALID,
    CASE WHEN CATEGORY IS NULL OR TRIM(CATEGORY) = '' THEN TRUE ELSE FALSE END AS IS_CATEGORY_MISSING,
    CURRENT_TIMESTAMP() AS SILVER_LOAD_TIMESTAMP,
    'BRONZE.PRODUCTS' AS SOURCE_TABLE
FROM BRONZE.PRODUCTS
WHERE PRODUCT_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY PRODUCT_ID ORDER BY CREATED_AT DESC) = 1;
