CREATE OR REPLACE TABLE SILVER.ORDERS AS
SELECT 
    O.ORDER_ID,
    O.CUSTOMER_ID,
    TO_TIMESTAMP(O.ORDER_DATE) AS ORDER_DATE,
    UPPER(TRIM(O.ORDER_STATUS)) AS ORDER_STATUS,
    CASE 
        WHEN O.TOTAL_AMOUNT < 0 THEN NULL
        ELSE O.TOTAL_AMOUNT 
    END AS ORDER_TOTAL,
    UPPER(TRIM(O.CURRENCY)) AS CURRENCY,
    DATE(TO_TIMESTAMP(O.ORDER_DATE)) AS ORDER_DATE_KEY,
    CASE WHEN O.CUSTOMER_ID IS NULL THEN TRUE ELSE FALSE END AS IS_CUSTOMER_MISSING,
    CASE WHEN O.TOTAL_AMOUNT IS NULL OR O.TOTAL_AMOUNT < 0 THEN TRUE ELSE FALSE END AS IS_AMOUNT_INVALID,
    CASE WHEN C.CUSTOMER_ID IS NULL THEN TRUE ELSE FALSE END AS IS_CUSTOMER_ORPHANED,
    CURRENT_TIMESTAMP() AS SILVER_LOAD_TIMESTAMP,
    'BRONZE.ORDERS' AS SOURCE_TABLE
FROM BRONZE.ORDERS O
LEFT JOIN SILVER.CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE O.ORDER_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY O.ORDER_ID ORDER BY O.ORDER_DATE DESC) = 1;
