CREATE OR REPLACE TABLE SILVER.ORDER_ITEMS AS
SELECT 
    OI.ORDER_ITEM_ID,
    OI.ORDER_ID,
    OI.PRODUCT_ID,
    CASE 
        WHEN OI.QUANTITY <= 0 THEN NULL
        ELSE OI.QUANTITY 
    END AS QUANTITY,
    CASE 
        WHEN OI.UNIT_PRICE < 0 THEN NULL
        ELSE OI.UNIT_PRICE 
    END AS UNIT_PRICE,
    CASE 
        WHEN OI.QUANTITY > 0 AND OI.UNIT_PRICE >= 0 
        THEN OI.QUANTITY * OI.UNIT_PRICE
        ELSE NULL
    END AS LINE_TOTAL,
    CASE WHEN OI.QUANTITY IS NULL OR OI.QUANTITY <= 0 THEN TRUE ELSE FALSE END AS IS_QUANTITY_INVALID,
    CASE WHEN OI.UNIT_PRICE IS NULL OR OI.UNIT_PRICE < 0 THEN TRUE ELSE FALSE END AS IS_PRICE_INVALID,
    CASE WHEN O.ORDER_ID IS NULL THEN TRUE ELSE FALSE END AS IS_ORDER_ORPHANED,
    CASE WHEN P.PRODUCT_ID IS NULL THEN TRUE ELSE FALSE END AS IS_PRODUCT_ORPHANED,
    CURRENT_TIMESTAMP() AS SILVER_LOAD_TIMESTAMP,
    'BRONZE.ORDER_ITEMS' AS SOURCE_TABLE
FROM BRONZE.ORDER_ITEMS OI
LEFT JOIN SILVER.ORDERS O ON OI.ORDER_ID = O.ORDER_ID
LEFT JOIN SILVER.PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
WHERE OI.ORDER_ITEM_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY OI.ORDER_ITEM_ID ORDER BY OI.ORDER_ITEM_ID) = 1;
