CREATE OR REPLACE TABLE SILVER.PAYMENTS AS
SELECT 
    P.PAYMENT_ID,
    P.ORDER_ID,
    TO_TIMESTAMP(P.PAYMENT_DATE) AS PAYMENT_DATE,
    UPPER(TRIM(P.PAYMENT_METHOD)) AS PAYMENT_METHOD,
    CASE 
        WHEN P.AMOUNT < 0 THEN NULL
        ELSE P.AMOUNT 
    END AS AMOUNT,
    UPPER(TRIM(P.CURRENCY)) AS CURRENCY,
    UPPER(TRIM(P.PAYMENT_STATUS)) AS PAYMENT_STATUS,
    CASE 
        WHEN UPPER(TRIM(P.PAYMENT_STATUS)) = 'SUCCESS' THEN TRUE
        ELSE FALSE
    END AS IS_PAYMENT_SUCCESSFUL,
    CASE WHEN P.AMOUNT IS NULL OR P.AMOUNT < 0 THEN TRUE ELSE FALSE END AS IS_AMOUNT_INVALID,
    CASE WHEN O.ORDER_ID IS NULL THEN TRUE ELSE FALSE END AS IS_ORDER_ORPHANED,
    CURRENT_TIMESTAMP() AS SILVER_LOAD_TIMESTAMP,
    'BRONZE.PAYMENTS' AS SOURCE_TABLE
FROM BRONZE.PAYMENTS P
LEFT JOIN SILVER.ORDERS O ON P.ORDER_ID = O.ORDER_ID
WHERE P.PAYMENT_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY P.PAYMENT_ID ORDER BY P.PAYMENT_DATE DESC) = 1;
