CREATE OR REPLACE TABLE SILVER.SHIPMENTS AS
SELECT 
    S.SHIPMENT_ID,
    S.ORDER_ID,
    TO_TIMESTAMP(S.SHIPMENT_DATE) AS SHIPMENT_DATE,
    CASE 
        WHEN UPPER(TRIM(S.SHIPMENT_STATUS)) IN ('DELIVERED') AND S.DELIVERY_DATE IS NOT NULL AND TRIM(S.DELIVERY_DATE) != ''
        THEN TO_TIMESTAMP(S.DELIVERY_DATE)
        WHEN UPPER(TRIM(S.SHIPMENT_STATUS)) IN ('IN_TRANSIT', 'CANCELLED', 'PENDING')
        THEN NULL
        ELSE TO_TIMESTAMP(S.DELIVERY_DATE)
    END AS DELIVERY_DATE,
    UPPER(TRIM(S.CARRIER)) AS CARRIER,
    UPPER(TRIM(S.SHIPMENT_STATUS)) AS SHIPMENT_STATUS,
    CASE 
        WHEN UPPER(TRIM(S.SHIPMENT_STATUS)) = 'DELIVERED' 
            AND S.DELIVERY_DATE IS NOT NULL 
            AND TRIM(S.DELIVERY_DATE) != ''
            AND S.SHIPMENT_DATE IS NOT NULL
        THEN DATEDIFF(DAY, TO_TIMESTAMP(S.SHIPMENT_DATE), TO_TIMESTAMP(S.DELIVERY_DATE))
        ELSE NULL
    END AS DELIVERY_DAYS,
    CASE 
        WHEN UPPER(TRIM(S.SHIPMENT_STATUS)) = 'DELIVERED' 
            AND S.DELIVERY_DATE IS NOT NULL 
            AND TRIM(S.DELIVERY_DATE) != ''
        THEN TRUE 
        ELSE FALSE 
    END AS IS_DELIVERED,
    CASE 
        WHEN S.DELIVERY_DATE IS NULL OR TRIM(S.DELIVERY_DATE) = '' 
        THEN TRUE 
        ELSE FALSE 
    END AS IS_DELIVERY_DATE_MISSING,
    CASE 
        WHEN UPPER(TRIM(S.SHIPMENT_STATUS)) IN ('IN_TRANSIT', 'CANCELLED', 'PENDING') 
            AND S.DELIVERY_DATE IS NOT NULL 
            AND TRIM(S.DELIVERY_DATE) != ''
        THEN TRUE 
        ELSE FALSE 
    END AS IS_DELIVERY_DATE_ILLOGICAL,
    CASE 
        WHEN S.DELIVERY_DATE IS NOT NULL AND S.SHIPMENT_DATE IS NOT NULL
             AND TO_TIMESTAMP(S.DELIVERY_DATE) < TO_TIMESTAMP(S.SHIPMENT_DATE)
        THEN TRUE 
        ELSE FALSE 
    END AS IS_DELIVERY_BEFORE_SHIPMENT,
    CASE WHEN O.ORDER_ID IS NULL THEN TRUE ELSE FALSE END AS IS_ORDER_ORPHANED,
    CURRENT_TIMESTAMP() AS SILVER_LOAD_TIMESTAMP,
    'BRONZE.SHIPMENTS' AS SOURCE_TABLE
FROM BRONZE.SHIPMENTS S
LEFT JOIN SILVER.ORDERS O ON S.ORDER_ID = O.ORDER_ID
WHERE S.SHIPMENT_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY S.SHIPMENT_ID ORDER BY S.SHIPMENT_DATE DESC) = 1;
