CREATE OR REPLACE TABLE GOLD.DIM_CUSTOMER AS
SELECT 
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    FULL_NAME,
    EMAIL,
    PHONE,
    COUNTRY,
    IS_ACTIVE,
    CUSTOMER_CREATED_AT,
    CURRENT_TIMESTAMP() AS GOLD_LOAD_TIMESTAMP
FROM SILVER.CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL;
