CREATE OR REPLACE TABLE GOLD.DIM_PRODUCT AS
SELECT 
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    PRICE,
    CURRENCY,
    IS_ACTIVE,
    PRODUCT_CREATED_AT,
    CURRENT_TIMESTAMP() AS GOLD_LOAD_TIMESTAMP
FROM SILVER.PRODUCTS
WHERE PRODUCT_ID IS NOT NULL;
