CREATE OR REPLACE TABLE GOLD.FACT_ORDERS AS
WITH payment_summary AS (
    SELECT 
        ORDER_ID,
        SUM(AMOUNT * ER.USD_CONVERSION_RATE) AS total_payment_amount_usd,
        MAX(CASE WHEN IS_PAYMENT_SUCCESSFUL THEN PAYMENT_STATUS ELSE NULL END) AS latest_payment_status,
        MAX(CASE WHEN IS_PAYMENT_SUCCESSFUL THEN PAYMENT_METHOD ELSE NULL END) AS latest_payment_method,
        MAX(IS_PAYMENT_SUCCESSFUL) AS has_successful_payment
    FROM SILVER.PAYMENTS P
    LEFT JOIN SILVER.EXCHANGE_RATES ER ON P.CURRENCY = ER.CURRENCY
    WHERE IS_ORDER_ORPHANED = FALSE
    GROUP BY ORDER_ID
)
SELECT 
    O.ORDER_ID,
    O.CUSTOMER_ID,
    O.ORDER_DATE,
    O.ORDER_DATE_KEY,
    O.ORDER_STATUS,
    O.CURRENCY AS ORIGINAL_CURRENCY,
    O.ORDER_TOTAL AS ORDER_TOTAL_ORIGINAL,
    O.ORDER_TOTAL * ER.USD_CONVERSION_RATE AS ORDER_TOTAL_USD,
    COUNT(OI.ORDER_ITEM_ID) AS order_item_count,
    SUM(OI.QUANTITY) AS total_quantity,
    SUM(OI.LINE_TOTAL * ER.USD_CONVERSION_RATE) AS order_revenue_usd,
    SUM(PROD.PRICE * OI.QUANTITY * ER_PROD.USD_CONVERSION_RATE) AS list_price_total_usd,
    SUM((PROD.PRICE - OI.UNIT_PRICE) * OI.QUANTITY * ER_PROD.USD_CONVERSION_RATE) AS total_discount_usd,
    COALESCE(PS.total_payment_amount_usd, 0) AS payment_amount_usd,
    PS.latest_payment_status AS payment_status,
    PS.latest_payment_method AS payment_method,
    CASE WHEN PS.has_successful_payment = TRUE THEN 1 ELSE 0 END AS is_paid,
    COALESCE(S.SHIPMENT_STATUS, 'NOT_SHIPPED') AS shipment_status,
    S.SHIPMENT_DATE,
    S.DELIVERY_DATE,
    S.DELIVERY_DAYS,
    CASE WHEN S.SHIPMENT_STATUS = 'DELIVERED' AND S.DELIVERY_DATE IS NOT NULL THEN 1 ELSE 0 END AS is_delivered,
    CASE 
        WHEN O.ORDER_STATUS = 'COMPLETED' 
             AND PS.has_successful_payment = TRUE 
             AND S.SHIPMENT_STATUS = 'DELIVERED' 
        THEN 1 
        ELSE 0 
    END AS is_fulfilled
FROM SILVER.ORDERS O
LEFT JOIN SILVER.EXCHANGE_RATES ER ON O.CURRENCY = ER.CURRENCY
LEFT JOIN SILVER.ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
LEFT JOIN SILVER.PRODUCTS PROD ON OI.PRODUCT_ID = PROD.PRODUCT_ID
LEFT JOIN SILVER.EXCHANGE_RATES ER_PROD ON PROD.CURRENCY = ER_PROD.CURRENCY
LEFT JOIN payment_summary PS ON O.ORDER_ID = PS.ORDER_ID
LEFT JOIN SILVER.SHIPMENTS S ON O.ORDER_ID = S.ORDER_ID
WHERE O.ORDER_ID IS NOT NULL
  AND O.IS_CUSTOMER_ORPHANED = FALSE
GROUP BY 
    O.ORDER_ID, O.CUSTOMER_ID, O.ORDER_DATE, O.ORDER_DATE_KEY, 
    O.ORDER_STATUS, O.CURRENCY, O.ORDER_TOTAL, ER.USD_CONVERSION_RATE,
    PS.total_payment_amount_usd, PS.latest_payment_status, PS.latest_payment_method, PS.has_successful_payment,
    S.SHIPMENT_STATUS, S.SHIPMENT_DATE, S.DELIVERY_DATE, S.DELIVERY_DAYS;
