CREATE OR REPLACE TABLE GOLD.FACT_ORDERS AS
SELECT 
    O.ORDER_ID,
    O.CUSTOMER_ID,
    O.ORDER_DATE,
    O.ORDER_DATE_KEY,
    O.ORDER_STATUS,
    O.CURRENCY,
    O.ORDER_TOTAL,
    COUNT(OI.ORDER_ITEM_ID) AS order_item_count,
    SUM(OI.QUANTITY) AS total_quantity,
    SUM(OI.LINE_TOTAL) AS order_revenue,
    SUM(PROD.PRICE * OI.QUANTITY) AS list_price_total,
    SUM((PROD.PRICE - OI.UNIT_PRICE) * OI.QUANTITY) AS total_discount,
    COALESCE(P.AMOUNT, 0) AS payment_amount,
    P.PAYMENT_STATUS,
    P.PAYMENT_METHOD,
    CASE WHEN P.IS_PAYMENT_SUCCESSFUL = TRUE THEN 1 ELSE 0 END AS is_paid,
    COALESCE(S.SHIPMENT_STATUS, 'NOT_SHIPPED') AS shipment_status,
    S.SHIPMENT_DATE,
    S.DELIVERY_DATE,
    S.DELIVERY_DAYS,
    CASE WHEN S.IS_DELIVERED = TRUE THEN 1 ELSE 0 END AS is_delivered,
    CASE 
        WHEN O.ORDER_STATUS = 'COMPLETED' AND P.IS_PAYMENT_SUCCESSFUL = TRUE AND S.IS_DELIVERED = TRUE 
        THEN 1 ELSE 0 
    END AS is_fulfilled,
    CURRENT_TIMESTAMP() AS GOLD_LOAD_TIMESTAMP
FROM SILVER.ORDERS O
LEFT JOIN SILVER.ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
LEFT JOIN SILVER.PRODUCTS PROD ON OI.PRODUCT_ID = PROD.PRODUCT_ID
LEFT JOIN SILVER.PAYMENTS P ON O.ORDER_ID = P.ORDER_ID
LEFT JOIN SILVER.SHIPMENTS S ON O.ORDER_ID = S.ORDER_ID
WHERE O.ORDER_ID IS NOT NULL
  AND O.IS_CUSTOMER_ORPHANED = FALSE
GROUP BY 
    O.ORDER_ID, O.CUSTOMER_ID, O.ORDER_DATE, O.ORDER_DATE_KEY, 
    O.ORDER_STATUS, O.CURRENCY, O.ORDER_TOTAL,
    P.AMOUNT, P.PAYMENT_STATUS, P.PAYMENT_METHOD, P.IS_PAYMENT_SUCCESSFUL,
    S.SHIPMENT_STATUS, S.SHIPMENT_DATE, S.DELIVERY_DATE, S.DELIVERY_DAYS, S.IS_DELIVERED;
