CREATE OR REPLACE TABLE GOLD.FACT_ORDER_ITEMS AS
SELECT 
    OI.ORDER_ITEM_ID,
    OI.ORDER_ID,
    OI.PRODUCT_ID,
    O.CUSTOMER_ID,
    O.ORDER_DATE,
    O.ORDER_DATE_KEY,
    P.CATEGORY AS product_category,
    OI.QUANTITY,
    P.PRICE AS list_price,
    OI.UNIT_PRICE AS actual_price,
    OI.LINE_TOTAL AS revenue,
    P.PRICE * OI.QUANTITY AS list_total,
    (P.PRICE - OI.UNIT_PRICE) AS discount_per_unit,
    (P.PRICE - OI.UNIT_PRICE) * OI.QUANTITY AS total_discount,
    CASE 
        WHEN P.PRICE > 0 THEN ROUND(((P.PRICE - OI.UNIT_PRICE) / P.PRICE) * 100, 2)
        ELSE 0 
    END AS discount_percentage,
    O.CURRENCY,
    O.ORDER_STATUS,
    CURRENT_TIMESTAMP() AS GOLD_LOAD_TIMESTAMP
FROM SILVER.ORDER_ITEMS OI
INNER JOIN SILVER.ORDERS O ON OI.ORDER_ID = O.ORDER_ID
INNER JOIN SILVER.PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
WHERE OI.ORDER_ITEM_ID IS NOT NULL
  AND OI.IS_ORDER_ORPHANED = FALSE
  AND OI.IS_PRODUCT_ORPHANED = FALSE
  AND OI.IS_QUANTITY_INVALID = FALSE
  AND OI.IS_PRICE_INVALID = FALSE;
