CREATE OR REPLACE TABLE GOLD.FACT_ORDER_ITEMS AS
SELECT 
    OI.ORDER_ITEM_ID,
    OI.ORDER_ID,
    OI.PRODUCT_ID,
    O.CUSTOMER_ID,
    O.ORDER_DATE,
    O.ORDER_DATE_KEY,
    P.CATEGORY AS product_category,
    P.CURRENCY AS ORIGINAL_CURRENCY,
    OI.QUANTITY,
    P.PRICE AS list_price_original,
    P.PRICE * ER.USD_CONVERSION_RATE AS list_price_usd,
    OI.UNIT_PRICE AS actual_price_original,
    OI.UNIT_PRICE * ER.USD_CONVERSION_RATE AS actual_price_usd,
    OI.LINE_TOTAL * ER.USD_CONVERSION_RATE AS revenue_usd,
    P.PRICE * OI.QUANTITY * ER.USD_CONVERSION_RATE AS list_total_usd,
    (P.PRICE - OI.UNIT_PRICE) * ER.USD_CONVERSION_RATE AS discount_per_unit_usd,
    (P.PRICE - OI.UNIT_PRICE) * OI.QUANTITY * ER.USD_CONVERSION_RATE AS total_discount_usd,
    CASE 
        WHEN P.PRICE > 0 THEN ROUND(((P.PRICE - OI.UNIT_PRICE) / P.PRICE) * 100, 2)
        ELSE 0 
    END AS discount_percentage,
    O.ORDER_STATUS,
    CURRENT_TIMESTAMP() AS GOLD_LOAD_TIMESTAMP
FROM SILVER.ORDER_ITEMS OI
INNER JOIN SILVER.ORDERS O ON OI.ORDER_ID = O.ORDER_ID
INNER JOIN SILVER.PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN SILVER.EXCHANGE_RATES ER ON P.CURRENCY = ER.CURRENCY
WHERE OI.ORDER_ITEM_ID IS NOT NULL
  AND OI.IS_ORDER_ORPHANED = FALSE
  AND OI.IS_PRODUCT_ORPHANED = FALSE
  AND OI.IS_QUANTITY_INVALID = FALSE
  AND OI.IS_PRICE_INVALID = FALSE;
