CREATE OR REPLACE TABLE GOLD.FACT_PAYMENTS AS
SELECT 
    P.PAYMENT_ID,
    P.ORDER_ID,
    O.CUSTOMER_ID,
    P.PAYMENT_DATE,
    DATE(P.PAYMENT_DATE) AS payment_date_key,
    P.PAYMENT_METHOD,
    P.PAYMENT_STATUS,
    P.IS_PAYMENT_SUCCESSFUL,
    P.CURRENCY AS ORIGINAL_CURRENCY,
    P.AMOUNT AS payment_amount_original,
    P.AMOUNT * ER_P.USD_CONVERSION_RATE AS payment_amount_usd,
    O.ORDER_TOTAL AS order_total_original,
    O.ORDER_TOTAL * ER_O.USD_CONVERSION_RATE AS order_total_usd,
    (P.AMOUNT * ER_P.USD_CONVERSION_RATE) - (O.ORDER_TOTAL * ER_O.USD_CONVERSION_RATE) AS payment_difference_usd,
    CURRENT_TIMESTAMP() AS GOLD_LOAD_TIMESTAMP
FROM SILVER.PAYMENTS P
INNER JOIN SILVER.ORDERS O ON P.ORDER_ID = O.ORDER_ID
LEFT JOIN SILVER.EXCHANGE_RATES ER_P ON P.CURRENCY = ER_P.CURRENCY
LEFT JOIN SILVER.EXCHANGE_RATES ER_O ON O.CURRENCY = ER_O.CURRENCY
WHERE P.PAYMENT_ID IS NOT NULL
  AND P.IS_ORDER_ORPHANED = FALSE
  AND P.IS_AMOUNT_INVALID = FALSE;
