CREATE OR REPLACE TABLE GOLD.FACT_PAYMENTS AS
SELECT 
    P.PAYMENT_ID,
    P.ORDER_ID,
    O.CUSTOMER_ID,
    P.PAYMENT_DATE,
    DATE(P.PAYMENT_DATE) AS payment_date_key,
    P.PAYMENT_METHOD,
    P.PAYMENT_STATUS,
    P.IS_PAYMENT_SUCCESSFUL,
    P.AMOUNT AS payment_amount,
    P.CURRENCY,
    O.ORDER_TOTAL,
    P.AMOUNT - O.ORDER_TOTAL AS payment_difference,
    CURRENT_TIMESTAMP() AS GOLD_LOAD_TIMESTAMP
FROM SILVER.PAYMENTS P
INNER JOIN SILVER.ORDERS O ON P.ORDER_ID = O.ORDER_ID
WHERE P.PAYMENT_ID IS NOT NULL
  AND P.IS_ORDER_ORPHANED = FALSE
  AND P.IS_AMOUNT_INVALID = FALSE;
