CREATE OR REPLACE TABLE GOLD.FACT_SHIPMENTS AS
SELECT 
    S.SHIPMENT_ID,
    S.ORDER_ID,
    O.CUSTOMER_ID,
    S.SHIPMENT_DATE,
    DATE(S.SHIPMENT_DATE) AS shipment_date_key,
    S.DELIVERY_DATE,
    DATE(S.DELIVERY_DATE) AS delivery_date_key,
    S.CARRIER,
    S.SHIPMENT_STATUS,
    S.DELIVERY_DAYS,
    S.IS_DELIVERED,
    O.ORDER_DATE,
    DATEDIFF(DAY, O.ORDER_DATE, S.SHIPMENT_DATE) AS days_to_ship,
    DATEDIFF(DAY, O.ORDER_DATE, S.DELIVERY_DATE) AS days_to_deliver,
    O.CURRENCY AS ORIGINAL_CURRENCY,
    O.ORDER_TOTAL AS order_total_original,
    O.ORDER_TOTAL * ER.USD_CONVERSION_RATE AS order_total_usd,
    CURRENT_TIMESTAMP() AS GOLD_LOAD_TIMESTAMP
FROM SILVER.SHIPMENTS S
INNER JOIN SILVER.ORDERS O ON S.ORDER_ID = O.ORDER_ID
LEFT JOIN SILVER.EXCHANGE_RATES ER ON O.CURRENCY = ER.CURRENCY
WHERE S.SHIPMENT_ID IS NOT NULL
  AND S.IS_ORDER_ORPHANED = FALSE;
