CREATE WAREHOUSE IF NOT EXISTS DE_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS ECOMMERCE_ANALYTICS;

USE DATABASE ECOMMERCE_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS MART;

USE SCHEMA BRONZE;

CREATE STAGE IF NOT EXISTS BRONZE_STAGE;
