CREATE OR REPLACE TABLE BRONZE.CUSTOMERS (
    CUSTOMER_ID STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE STRING,
    COUNTRY STRING,
    CREATED_AT STRING,
    IS_ACTIVE STRING,
    INGESTION_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
