CREATE OR REPLACE TABLE BRONZE.PRODUCTS (
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE STRING,
    CURRENCY STRING,
    IS_ACTIVE STRING,
    CREATED_AT STRING,
    INGESTION_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
