CREATE OR REPLACE TABLE BRONZE.ORDERS (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_DATE STRING,
    ORDER_STATUS STRING,
    TOTAL_AMOUNT STRING,
    CURRENCY STRING,
    INGESTION_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
