CREATE OR REPLACE TABLE BRONZE.ORDER_ITEMS (
    ORDER_ITEM_ID STRING,
    ORDER_ID STRING,
    PRODUCT_ID STRING,
    QUANTITY STRING,
    UNIT_PRICE STRING,
    INGESTION_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
