CREATE OR REPLACE TABLE BRONZE.PAYMENTS (
    PAYMENT_ID STRING,
    ORDER_ID STRING,
    PAYMENT_DATE STRING,
    PAYMENT_METHOD STRING,
    AMOUNT STRING,
    CURRENCY STRING,
    PAYMENT_STATUS STRING,
    INGESTION_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
