CREATE OR REPLACE TABLE BRONZE.SHIPMENTS (
    SHIPMENT_ID STRING,
    ORDER_ID STRING,
    SHIPMENT_DATE STRING,
    DELIVERY_DATE STRING,
    CARRIER STRING,
    SHIPMENT_STATUS STRING,
    INGESTION_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
